server:
  port: 8088

feign-client:
  currency-api:
    url: https://openexchangerates.org/api/
    options:
      latest: latest.json
      historical: historical
      app-id: aeafe872a06a4529b38b8226970ef527
      objective-currency-code: USD
  gif-api:
    url: api.giphy.com/v1/gifs/search/
    options:
      api-key: oPIMd6yEozhTyom1QrGcgeORY83ygDTU
      limit: 30
      positive-search-query: rich
      negative-search-query: broke
      image-object-name: original
      image-type-name: url



logging:
  level:
    com.andrey.gifcurrencyservice.feign.*: DEBUG
  file:
    name: logs/OpenFeign.log